export const FETCH_MAIN_GAME_DATA_SUCCESS = 'FETCH_MAIN_GAME_DATA_SUCCESS';
export const FETCH_MAIN_GAME_DATA_FAILURE = 'FETCH_MAIN_GAME_DATA_FAILURE';
export const MAKE_TURN = 'MAKE_TURN';

export const FETCH_SCORE_DATA_SUCCESS = 'FETCH_SCORE_DATA_SUCCESS';
export const FETCH_SCORE_DATA_FAILURE = 'FETCH_SCORE_DATA_FAILURE';